add_rules("mode.debug", "mode.release")
add_requires("glad 0.1.36", "glfw 3.4")

target("renderImage")
    set_kind("binary")
    add_files("render_image.c")
    add_includedirs("../")
    add_headerfiles("(../stb_image.h)")
    add_packages("glad", "glfw")
    set_targetdir("$(projectdir)/bin/$(mode)")